export const recipes = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 7,
    gaps: 'no',
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 11,
    healthScore: 41,
    sourceName: 'foodista.com',
    pricePerServing: 268.73,
    id: 643061,
    title: 'Flank Steak with Herbed Salsa',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      'https://www.foodista.com/recipe/GJV558KY/flank-steak-with-herbed-salsa',
    image: 'https://img.spoonacular.com/recipes/715415-312x231.jpg',
    imageType: 'jpg',
    summary:
      'Flank Steak with Herbed Salsan is a <b>gluten free, dairy free, paleolithic, and primal</b> recipe with 4 servings. One serving contains <b>301 calories</b>, <b>25g of protein</b>, and <b>20g of fat</b>. For <b>$2.69 per serving</b>, this recipe <b>covers 18%</b> of your daily requirements of vitamins and minerals. It can be enjoyed any time, but it is especially good for <b>valentin day</b>. 11 person were glad they tried this recipe. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. It is a <b>rather cheap</b> recipe for fans of Mexican food. A mixture of juice of lime, extra virgin olive oil, scallions, and a handful of other ingredients are all it takes to make this recipe so yummy. It is brought to you by Foodista. It works well as a main course. Overall, this recipe earns an <b>outstanding spoonacular score of 88%</b>. Try <a href="https://spoonacular.com/recipes/herbed-flank-steak-with-tomatoes-81327">Herbed Flank Steak With Tomatoes</a>, <a href="https://spoonacular.com/recipes/flank-steak-with-salsa-verde-201773">Flank Steak with Salsa Verde</a>, and <a href="https://spoonacular.com/recipes/flank-steak-with-salsa-verde-305256">Flank Steak with Salsa Verde</a> for similar recipes.',
    cuisines: ['Mexican'],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: [
      'gluten free',
      'dairy free',
      'paleolithic',
      'primal',
      'whole 30',
      'ketogenic',
    ],
    occasions: ["valentine's day", "father's day"],
    instructions:
      '<ol><li>Preheat a grill pan or light a grill.</li><li>In a medium bowl, combine the tomatoes with the scallions, cilantro, Jalapeno, garlic and lemon  lime juice. Season the salsa with salt and freshly ground pepper.</li><li>Season with salt and pepper the flank steak.</li><li>Using a grill pan brush a shadow of oil on the bottom of it. Place the pan over high heat and when hot add the flank steak. Cook until nicely charred outside and medium rare inside. About 3 minutes per side.</li><li>Transfer the steak to a carving board and let rest for 5 minutes.</li><li>Thinly slice the steak across the grain and serve with the herbed salsa.</li></ol>',
    originalId: null,
    spoonacularScore: 89.79270935058594,
    spoonacularSourceUrl:
      'https://spoonacular.com/flank-steak-with-herbed-salsa-643061',
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 16,
    gaps: 'no',
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 34,
    healthScore: 8,

    sourceName: 'foodista.com',
    pricePerServing: 190.73,
    id: 633651,
    title: 'Baked Honey Sriracha Chicken Wings',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      'https://www.foodista.com/recipe/VK2D4Q2P/baked-honey-sriracha-chicken-wings',
    image: 'https://img.spoonacular.com/recipes/633651-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Forget going out to eat or ordering takeout every time you crave American food. Try making Baked Honey Sriracha Chicken Wings at home. This gluten free and dairy free recipe serves 4 and costs <b>$1.91 per serving</b>. One serving contains <b>506 calories</b>, <b>30g of protein</b>, and <b>32g of fat</b>. 34 people have tried and liked this recipe. This recipe from Foodista requires brown sugar, chicken wings, sriracha, and ground ginger. It works well as a hor d\'oeuvre. From preparation to the plate, this recipe takes about <b>45 minutes</b>. With a spoonacular <b>score of 57%</b>, this dish is good. <a href="https://spoonacular.com/recipes/baked-honey-sriracha-chicken-wings-590767">Baked Honey-Sriracha Chicken Wings</a>, <a href="https://spoonacular.com/recipes/honey-baked-sriracha-chicken-wings-163041">Honey-Baked Sriracha Chicken Wings</a>, and <a href="https://spoonacular.com/recipes/baked-honey-sriracha-wings-1522195">Baked Honey Sriracha Wings</a> are very similar to this recipe.',
    cuisines: ['American'],
    dishTypes: [
      'antipasti',
      'lunch',
      'main course',
      'starter',
      'snack',
      'appetizer',
      'main dish',
      'antipasto',
      "hor d'oeuvre",
      'dinner',
    ],
    diets: ['gluten free', 'dairy free'],
    occasions: [],
    instructions:
      '<ol><li>Directions:</li><li>1. Preheat oven to 425 degrees Fahrenheit. Place chicken on baking sheets ( you will need 2). Add olive oil, salt and pepper to chicken. Toss chicken on baking sheet. Place in a single layer, making sure that no chicken touch. Cook for 10 minutes, then flip and cook for 10 more.</li><li>2. Preheat broiler.Take chicken out. Spoon about 1 TBSP of sauce over each wing. Place in oven and cook until turned slightly browned, about 5 minutes. Flip the chicken so that all have skin side up. Pour the rest of the sauce over chicken. Place back in broiler and cook till skin is crispy, about 10 minutes.</li><li>3. Once done, toss chicken with sauce created on pan. Serve and garnish with cilantro.</li><li>ENJOY!</li></ol>',
    originalId: null,
    spoonacularScore: 59.66693878173828,
    spoonacularSourceUrl:
      'https://spoonacular.com/baked-honey-sriracha-chicken-wings-633651',
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 21,
    gaps: 'no',
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 2,
    healthScore: 31,

    sourceName: 'foodista.com',
    pricePerServing: 276.83,
    id: 637999,
    title: 'Chicken Burritos',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      'https://www.foodista.com/recipe/YCKK77YK/chicken-burrito-by-bing',
    image: 'https://img.spoonacular.com/recipes/665642-556x370.jpg',
    imageType: 'jpg',
    summary:
      'If you have approximately <b>45 minutes</b> to spend in the kitchen, Chicken Burritos might be a tremendous <b>dairy free</b> recipe to try. This main course has <b>713 calories</b>, <b>32g of protein</b>, and <b>50g of fat</b> per serving. For <b>$2.77 per serving</b>, this recipe <b>covers 35%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. 2 people were glad they tried this recipe. If you have avocadoes, onion, cilantro, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. This recipe is typical of Mexican cuisine. With a spoonacular <b>score of 77%</b>, this dish is solid. Try <a href="https://spoonacular.com/recipes/chicken-burritos-1345431">Chicken Burritos</a>, <a href="https://spoonacular.com/recipes/chicken-burritos-81171">Chicken Burritos</a>, and <a href="https://spoonacular.com/recipes/chicken-burritos-1326807">Chicken Burritos</a> for similar recipes.',
    cuisines: ['Mexican'],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['dairy free'],
    occasions: [],
    instructions:
      '<ol><li>Cut the chicken thighs into one inch sized pieces.</li><li>Add about 2 teaspoons of salt and 2 teaspoons of pepper. Or do what I always do for dishes that call for salt and pepper. I use Masterfoods Garlic Pepper. Give it a good sprinkle, about 1 tablespoon of it. Set aside to marinate for a couple of hours.</li><li>Slice the top of the tomatoes off.</li><li>Using a small spoon, scoop out the soft insides of the tomatoes. This reduces the moisture in the dish and prevents sogginess.</li><li>Chop the tomatoes up into small bits.</li><li>Chop the onions into small bits.</li><li>Place the onions and tomatoes in a large bowl.</li><li>Chop up a bunch of cilantro. Use as much or as little as you like.</li><li>Add the cilantro to the onions-tomatoes mixture. Toss together and set aside.</li><li>Cut a slit round an avocado, against its seed.</li><li>Holding each side of the cut avocado, twist the avocado open to reveal the seed.</li><li>Remove the seed and scoop out the flesh. Place the avocado flesh in a large bowl and mash it up evenly till it becomes creamy.</li><li>Add the tomatoes mixture to the avocados.</li><li>Combine well.</li><li>Squeeze in juice from one lemon.</li><li>Add a generous portion of salt to taste. About 1 to 2 teaspoons.</li><li>At this point, youll have guacamole. If you like, dish it up in a serving bowl and serve it with chips.</li><li>Now cook the chicken. Heat a pan with a few tablespoons of cooking oil till its very hot. It has to be very hot or the chicken wont brown.</li><li>Add the chicken to the pan. Be careful! Itll sizzle and splatter.</li><li>Turn the pieces over to brown the other side after a few minutes.</li><li>When the chicken are browned, remove them from the pan and set aside at a warm place.</li><li>Using a clean, dry pan, toast the tortillas one at a time on each side.</li><li>They are ready to be used when they are soft and warm.</li><li>Add a serving of the guacamole mixture.</li><li>Add a serving of the chicken.</li><li>Quickly wrap the burrito up. If it cools, the tortilla will crack and it would be impossible to roll it up.</li><li>Roll over once. Fold in the sides, and roll over again till its fully wrapped.</li><li>Serve immediately or wrap in aluminum foil and keep them in the oven till ready to eat.</li></ol>',
    originalId: null,
    spoonacularScore: 78.79966735839844,
    spoonacularSourceUrl: 'https://spoonacular.com/chicken-burritos-637999',
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 28,
    gaps: 'no',
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 3,
    healthScore: 27,

    sourceName: 'foodista.com',
    pricePerServing: 260.07,
    id: 633884,
    title: 'Baked Ziti Or Rigatoni',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      'https://www.foodista.com/recipe/LJ86FGZ5/baked-ziti-or-rigatoni',
    image: 'https://img.spoonacular.com/recipes/655575-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Baked Ziti Or Rigatoni is a Mediterranean recipe that serves 4. This main course has <b>869 calories</b>, <b>45g of protein</b>, and <b>32g of fat</b> per serving. For <b>$2.6 per serving</b>, this recipe <b>covers 33%</b> of your daily requirements of vitamins and minerals. This recipe from Foodista requires ziti, spaghetti sauce, parmesan cheese, and ricotta. Not a lot of people made this recipe, and 3 would say it hit the spot. From preparation to the plate, this recipe takes around <b>45 minutes</b>. With a spoonacular <b>score of 75%</b>, this dish is good. Try <a href="https://spoonacular.com/recipes/rigatoni-al-forno-baked-rigatoni-with-roasted-asparagus-and-on-115058">Rigatoni Al Forno (Baked Rigatoni) with Roasted Asparagus and On</a>, <a href="https://spoonacular.com/recipes/baked-rigatoni-408338">Baked Rigatoni</a>, and <a href="https://spoonacular.com/recipes/baked-rigatoni-138827">Baked Rigatoni</a> for similar recipes.',
    cuisines: ['Mediterranean', 'Italian', 'European'],
    dishTypes: ['side dish', 'lunch', 'main course', 'main dish', 'dinner'],
    diets: [],
    occasions: [],
    instructions:
      '<ol><li>Mix first 4 ingredients and 1 1/2 cups of spaghetti sauce in a bowl. In a 2 1/2 quart baking dish spread 1/2 cup spaghetti sauce. Add ziti mixture and top with remaining 1 1/2 cups of spaghetti sauce. Sprinkle with 1/2 cup of Parmesan cheese. Bake at 375 degrees for 30 minutes or until top slightly browned.</li></ol>',
    originalId: null,
    spoonacularScore: 63.24042510986328,
    spoonacularSourceUrl:
      'https://spoonacular.com/baked-ziti-or-rigatoni-633884',
  },
  {
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 3,
    gaps: 'no',
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 36,
    healthScore: 13,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 71.47,
    id: 648643,
    title: "Julia Child's Vichyssoise",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      'https://www.foodista.com/recipe/JBVYH2GY/julia-child-s-vichyssoise',
    image: 'https://img.spoonacular.com/recipes/648643-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Julia Child\'s Vichyssoise takes approximately <b>45 minutes</b> from beginning to end. This recipe makes 6 servings with <b>153 calories</b>, <b>4g of protein</b>, and <b>4g of fat</b> each. For <b>71 cents per serving</b>, this recipe <b>covers 10%</b> of your daily requirements of vitamins and minerals. 36 people were impressed by this recipe. It works well as a side dish. A mixture of leeks, salt or, water, and a handful of other ingredients are all it takes to make this recipe so yummy. It is a good option if you\'re following a <b>gluten free and lacto ovo vegetarian</b> diet. It is brought to you by Foodista. All things considered, we decided this recipe <b>deserves a spoonacular score of 70%</b>. This score is good. Similar recipes include <a href="https://spoonacular.com/recipes/julia-childs-ratatouille-1202455">Julia Child\'s Ratatouille</a>, <a href="https://spoonacular.com/recipes/julia-childs-ratatouille-648641">Julia Child\'s Ratatouille</a>, and <a href="https://spoonacular.com/recipes/julia-childs-floating-islands-573653">Julia Child\'s Floating Islands</a>.',
    cuisines: [],
    dishTypes: ['side dish'],
    diets: ['gluten free', 'lacto ovo vegetarian'],
    occasions: [],
    instructions:
      'Bring the leeks, potatoes and water to the boil in the saucepan. Salt lightly, cover partially, and simmer 20-30 minutes, or until the vegetables are tender.\nPure the soup if you wish. Taste, and correct seasoning.\nAfter chilling the soup, you may wish to stir in a little more cream. Taste carefully again, and correct the seasoning.\nTop each serving with a sprinkle of chives or parsley and a drizzle or dollop of crme frache.',
    originalId: null,
    spoonacularScore: 72.07901000976562,
    spoonacularSourceUrl:
      'https://spoonacular.com/julia-childs-vichyssoise-648643',
  },
  {
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 3,
    gaps: 'no',
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 4,
    healthScore: 2,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 89.25,
    id: 642406,
    title: 'Endive Appetizer With Blue Cheese, Dried Cranberries and Walnuts',
    readyInMinutes: 20,
    servings: 8,
    sourceUrl:
      'https://www.foodista.com/recipe/ZHRS3PMK/endive-with-blue-cheese-dried-cranberries-and-walnuts',
    image: 'https://img.spoonacular.com/recipes/646738-556x370.jpg',
    imageType: 'jpg',
    summary:
      'The recipe Endive Appetizer With Blue Cheese, Dried Cranberries and Walnuts can be made <b>in roughly 20 minutes</b>. One portion of this dish contains approximately <b>4g of protein</b>, <b>10g of fat</b>, and a total of <b>183 calories</b>. This recipe serves 8. For <b>89 cents per serving</b>, this recipe <b>covers 5%</b> of your daily requirements of vitamins and minerals. 4 people have made this recipe and would make it again. It can be enjoyed any time, but it is especially good for <b>Christmas</b>. It is brought to you by Foodista. Only a few people really liked this hor d\'oeuvre. A mixture of apples, cranberries, walnut pieces, and a handful of other ingredients are all it takes to make this recipe so delicious. It is a good option if you\'re following a <b>gluten free, lacto ovo vegetarian, and primal</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 32%</b>. This score is rather bad. Similar recipes are <a href="https://spoonacular.com/recipes/endive-appetizer-with-blue-cheese-dried-cranberries-and-walnuts-1202357">Endive Appetizer With Blue Cheese, Dried Cranberries and Walnuts</a>, <a href="https://spoonacular.com/recipes/endive-boats-with-pears-blue-cheese-and-walnuts-706715">Endive Boats with Pears, Blue Cheese, and Walnuts</a>, and <a href="https://spoonacular.com/recipes/green-beans-with-walnuts-cranberries-and-blue-cheese-408146">Green Beans with Walnuts, Cranberries and Blue Cheese</a>.',
    cuisines: [],
    dishTypes: [
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre",
    ],
    diets: ['gluten free', 'lacto ovo vegetarian', 'primal'],
    occasions: ['christmas'],
    instructions:
      '<ol><li>Toast walnuts in a dry skillet over medium heat for two minutes until fragrant. Set aside and cool.</li><li>Arrange apple slices on one platter, and endive leaves on other platter.</li><li>In a medium bowl combine cooled walnuts, dried cranberries and blue cheese.</li><li>Top endive leaves with 1 tablespoon cheese mix and a drop or two of balsamic dressing.</li><li>Put remaining cheese, nuts and blue cheese in a bowl to serve with apple slices.</li></ol>',
    originalId: null,
    spoonacularScore: 34.95064163208008,
    spoonacularSourceUrl:
      'https://spoonacular.com/endive-appetizer-with-blue-cheese-dried-cranberries-and-walnuts-642406',
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 2,
    gaps: 'no',
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 2,
    healthScore: 21,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 301.16,
    id: 651455,
    title: 'Mediterranean-Style Haddock',
    readyInMinutes: 45,
    servings: 2,
    sourceUrl:
      'https://www.foodista.com/recipe/KQWX4NZT/mediterranean-style-haddock',
    image: 'https://img.spoonacular.com/recipes/651455-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Mediterranean-Style Haddock might be just the main course you are searching for. This recipe makes 2 servings with <b>155 calories</b>, <b>20g of protein</b>, and <b>3g of fat</b> each. For <b>$3.01 per serving</b>, this recipe <b>covers 17%</b> of your daily requirements of vitamins and minerals. 2 people have made this recipe and would make it again. This recipe from Foodista requires oregano, garlic, bell pepper, and ground tomatoes. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. It is a good option if you\'re following a <b>gluten free, dairy free, paleolithic, and primal</b> diet. With a spoonacular <b>score of 63%</b>, this dish is pretty good. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/mediterranean-style-haddock-1281965">Mediterranean-Style Haddock</a>, <a href="https://spoonacular.com/recipes/mediterranean-style-haddock-1408085">Mediterranean-Style Haddock</a>, and <a href="https://spoonacular.com/recipes/mediterranean-style-paninis-516699">Mediterranean Style Paninis</a>.',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: [
      'gluten free',
      'dairy free',
      'paleolithic',
      'primal',
      'pescatarian',
    ],
    occasions: [],
    instructions:
      'Preheat oven to 350. Heat oil in a small skillet over medium heat. Add red pepper and onion and saut for 7 minutes, or until slightly softened. Add garlic and stir for 30 seconds.\nAdd white wine to deglaze the pan, followed by ground tomatoes, oregano, salt, and pepper. Stir and let simmer for 2 minutes.\nPlace the fish in a single layer in a small oven-safe baking dish and cover with the tomato sauce. Sprinkle with the feta cheese.\nBake for 20 minutes. Serve.',
    originalId: null,
    spoonacularScore: 69.25664520263672,
    spoonacularSourceUrl:
      'https://spoonacular.com/mediterranean-style-haddock-651455',
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 3,
    gaps: 'no',
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 6,
    healthScore: 1,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 63.15,
    id: 640273,
    title: 'Crab Cake Stuffed Shrimp',
    readyInMinutes: 45,
    servings: 24,
    sourceUrl:
      'https://www.foodista.com/recipe/MMGP257M/crab-cake-stuffed-shrimp',
    image: 'https://img.spoonacular.com/recipes/640273-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Crab Cake Stuffed Shrimp requires roughly <b>45 minutes</b> from start to finish. Watching your figure? This pescatarian recipe has <b>94 calories</b>, <b>5g of protein</b>, and <b>6g of fat</b> per serving. For <b>63 cents per serving</b>, you get a hor d\'oeuvre that serves 24. Not a lot of people made this recipe, and 6 would say it hit the spot. This recipe from Foodista requires garlic, ground pepper, bell pepper, and old bay seasoning. Taking all factors into account, this recipe <b>earns a spoonacular score of 20%</b>, which is not so tremendous. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/crab-cake-stuffed-shrimp-1156320">Crab Cake Stuffed Shrimp</a>, <a href="https://spoonacular.com/recipes/crab-stuffed-shrimp-244924">Crab Stuffed Shrimp</a>, and <a href="https://spoonacular.com/recipes/crab-stuffed-shrimp-11095">Crab Stuffed Shrimp</a>.',
    cuisines: [],
    dishTypes: [
      'antipasti',
      'starter',
      'snack',
      'appetizer',
      'antipasto',
      "hor d'oeuvre",
    ],
    diets: ['pescatarian'],
    occasions: [],
    instructions:
      'Line a baking sheet with parchment paper.\nHeat 5 tablespoons butter until melted.\nAdd onion and saute until translucent.\nAdd bell pepper, remaining 5 tablespoons butter, wine and garlic.\nCook until tender (about 4 minutes).\nIn a large bowl, add crab meat, onion mixture, cracker crumbs, panko, red pepper, Old Bay, salt and pepper.\nStir to combine.\nCover and refrigerate for at least 1 hour to 24 hours.\nPreheat oven to 350 degrees.\nUsing a sharp knife and staring at the tail end, butterfly each shrimp.\nPlace each butterflied shrimp on prepared pan, pressing to flatten.\nForm about 3 tablespoons crab mixture into an ball.\nPlace on top of shrimp, pressing the shrimp tail over the crab.\nRepeat with remaining shrimp and crab mixture.\nBake 10 to 15 minutes.\nOPTIONAL:  Squeeze fresh lemon juice over cooked appetizer.\nServe immediately.',
    originalId: null,
    spoonacularScore: 29.873157501220703,
    spoonacularSourceUrl:
      'https://spoonacular.com/crab-cake-stuffed-shrimp-640273',
  },
];

export const recipe = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: true,
  veryHealthy: true,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 12,
  gaps: 'no',
  preparationMinutes: null,
  cookingMinutes: null,
  aggregateLikes: 3,
  healthScore: 6,
  creditsText: 'foodista.com',
  sourceName: 'foodista.com',
  pricePerServing: 77.21,
  extendedIngredients: [
    {
      id: 1001,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'butter-sliced.jpg',
      consistency: 'SOLID',
      name: 'butter',
      nameClean: 'butter',
      original: '1 teaspoon butter',
      originalName: 'butter',
      amount: 1.0,
      unit: 'teaspoon',
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
        metric: {
          amount: 1.0,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
      },
    },
  ],
  id: 642583,
  title: 'Farfalle with Peas, Ham and Cream',
  readyInMinutes: 30,
  servings: 4,
  sourceUrl:
    'http://www.foodista.com/recipe/V7DKVTXY/farfalle-with-peas-ham-and-cream',
  image: '/images/recipe-week.jpg',
  imageType: 'jpg',
  nutrition: {
    nutrients: [
      {
        name: 'Calories',
        amount: 397.04,
        unit: 'kcal',
        percentOfDailyNeeds: 19.85,
      },
      {
        name: 'Fat',
        amount: 16.0,
        unit: 'g',
        percentOfDailyNeeds: 24.61,
      },
      {
        name: 'Saturated Fat',
        amount: 9.72,
        unit: 'g',
        percentOfDailyNeeds: 60.73,
      },
      {
        name: 'Carbohydrates',
        amount: 48.3,
        unit: 'g',
        percentOfDailyNeeds: 16.1,
      },
      {
        name: 'Net Carbohydrates',
        amount: 44.44,
        unit: 'g',
        percentOfDailyNeeds: 16.16,
      },
      {
        name: 'Sugar',
        amount: 4.53,
        unit: 'g',
        percentOfDailyNeeds: 5.04,
      },
      {
        name: 'Cholesterol',
        amount: 45.21,
        unit: 'mg',
        percentOfDailyNeeds: 15.07,
      },
      {
        name: 'Sodium',
        amount: 425.06,
        unit: 'mg',
        percentOfDailyNeeds: 18.48,
      },
      {
        name: 'Alcohol',
        amount: 0.0,
        unit: 'g',
        percentOfDailyNeeds: 100.0,
      },
      {
        name: 'Alcohol %',
        amount: 0.0,
        unit: '%',
        percentOfDailyNeeds: 100.0,
      },
      {
        name: 'Protein',
        amount: 14.73,
        unit: 'g',
        percentOfDailyNeeds: 29.45,
      },
      {
        name: 'Selenium',
        amount: 39.76,
        unit: 'µg',
        percentOfDailyNeeds: 56.8,
      },
      {
        name: 'Manganese',
        amount: 0.67,
        unit: 'mg',
        percentOfDailyNeeds: 33.27,
      },
      {
        name: 'Phosphorus',
        amount: 249.29,
        unit: 'mg',
        percentOfDailyNeeds: 24.93,
      },
      {
        name: 'Calcium',
        amount: 188.88,
        unit: 'mg',
        percentOfDailyNeeds: 18.89,
      },
      {
        name: 'Vitamin C',
        amount: 14.68,
        unit: 'mg',
        percentOfDailyNeeds: 17.79,
      },
      {
        name: 'Vitamin A',
        amount: 843.5,
        unit: 'IU',
        percentOfDailyNeeds: 16.87,
      },
      {
        name: 'Fiber',
        amount: 3.86,
        unit: 'g',
        percentOfDailyNeeds: 15.43,
      },
      {
        name: 'Magnesium',
        amount: 49.26,
        unit: 'mg',
        percentOfDailyNeeds: 12.31,
      },
      {
        name: 'Copper',
        amount: 0.23,
        unit: 'mg',
        percentOfDailyNeeds: 11.65,
      },
      {
        name: 'Zinc',
        amount: 1.66,
        unit: 'mg',
        percentOfDailyNeeds: 11.04,
      },
      {
        name: 'Vitamin B2',
        amount: 0.18,
        unit: 'mg',
        percentOfDailyNeeds: 10.55,
      },
      {
        name: 'Vitamin B1',
        amount: 0.16,
        unit: 'mg',
        percentOfDailyNeeds: 10.51,
      },
      {
        name: 'Vitamin K',
        amount: 10.3,
        unit: 'µg',
        percentOfDailyNeeds: 9.81,
      },
      {
        name: 'Folate',
        amount: 35.74,
        unit: 'µg',
        percentOfDailyNeeds: 8.94,
      },
      {
        name: 'Vitamin B3',
        amount: 1.76,
        unit: 'mg',
        percentOfDailyNeeds: 8.82,
      },
      {
        name: 'Vitamin B6',
        amount: 0.16,
        unit: 'mg',
        percentOfDailyNeeds: 8.13,
      },
      {
        name: 'Iron',
        amount: 1.4,
        unit: 'mg',
        percentOfDailyNeeds: 7.78,
      },
      {
        name: 'Potassium',
        amount: 253.43,
        unit: 'mg',
        percentOfDailyNeeds: 7.24,
      },
      {
        name: 'Vitamin B5',
        amount: 0.41,
        unit: 'mg',
        percentOfDailyNeeds: 4.13,
      },
      {
        name: 'Vitamin D',
        amount: 0.54,
        unit: 'µg',
        percentOfDailyNeeds: 3.59,
      },
      {
        name: 'Vitamin B12',
        amount: 0.2,
        unit: 'µg',
        percentOfDailyNeeds: 3.33,
      },
      {
        name: 'Vitamin E',
        amount: 0.44,
        unit: 'mg',
        percentOfDailyNeeds: 2.93,
      },
    ],
    properties: [
      {
        name: 'Glycemic Index',
        amount: 40.83,
        unit: '',
      },
      {
        name: 'Glycemic Load',
        amount: 18.32,
        unit: '',
      },
    ],
    flavonoids: [
      {
        name: 'Cyanidin',
        amount: 0.0,
        unit: '',
      },
      {
        name: 'Petunidin',
        amount: 0.0,
        unit: '',
      },

      {
        name: 'Gallocatechin',
        amount: 0.0,
        unit: 'mg',
      },
    ],
    ingredients: [
      {
        id: 1001,
        name: 'butter',
        amount: 0.25,
        unit: 'teaspoon',
        nutrients: [
          {
            name: 'Choline',
            amount: 0.23,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Alcohol',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 100.0,
          },
          {
            name: 'Vitamin B1',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 10.51,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0.04,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Fat',
            amount: 1.01,
            unit: 'g',
            percentOfDailyNeeds: 24.61,
          },
          {
            name: 'Cholesterol',
            amount: 2.69,
            unit: 'mg',
            percentOfDailyNeeds: 15.07,
          },
          {
            name: 'Vitamin B12',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 3.33,
          },
          {
            name: 'Calcium',
            amount: 0.3,
            unit: 'mg',
            percentOfDailyNeeds: 18.89,
          },
          {
            name: 'Selenium',
            amount: 0.01,
            unit: 'µg',
            percentOfDailyNeeds: 56.8,
          },
          {
            name: 'Phosphorus',
            amount: 0.3,
            unit: 'mg',
            percentOfDailyNeeds: 24.93,
          },
          {
            name: 'Vitamin B3',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 8.82,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 16.16,
          },
          {
            name: 'Vitamin D',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 3.59,
          },
          {
            name: 'Trans Fat',
            amount: 0.04,
            unit: 'g',
            percentOfDailyNeeds: 409.75,
          },
          {
            name: 'Folic Acid',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Folate',
            amount: 0.04,
            unit: 'µg',
            percentOfDailyNeeds: 8.94,
          },
          {
            name: 'Vitamin K',
            amount: 0.09,
            unit: 'µg',
            percentOfDailyNeeds: 9.81,
          },
          {
            name: 'Copper',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 11.65,
          },
          {
            name: 'Iron',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 7.78,
          },
          {
            name: 'Magnesium',
            amount: 0.03,
            unit: 'mg',
            percentOfDailyNeeds: 12.31,
          },
          {
            name: 'Lycopene',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin B5',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Manganese',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 33.27,
          },
          {
            name: 'Fluoride',
            amount: 0.04,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Protein',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 29.45,
          },
          {
            name: 'Fiber',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 15.43,
          },
          {
            name: 'Vitamin B2',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 10.55,
          },
          {
            name: 'Sodium',
            amount: 8.04,
            unit: 'mg',
            percentOfDailyNeeds: 18.48,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0.26,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin E',
            amount: 0.03,
            unit: 'mg',
            percentOfDailyNeeds: 2.93,
          },
          {
            name: 'Carbohydrates',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 16.1,
          },
          {
            name: 'Vitamin B6',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 8.13,
          },
          {
            name: 'Sugar',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 5.04,
          },
          {
            name: 'Zinc',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 11.04,
          },
          {
            name: 'Saturated Fat',
            amount: 0.64,
            unit: 'g',
            percentOfDailyNeeds: 60.73,
          },
          {
            name: 'Vitamin A',
            amount: 31.24,
            unit: 'IU',
            percentOfDailyNeeds: 16.87,
          },
          {
            name: 'Vitamin C',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 17.79,
          },
          {
            name: 'Potassium',
            amount: 0.3,
            unit: 'mg',
            percentOfDailyNeeds: 7.24,
          },
          {
            name: 'Calories',
            amount: 8.96,
            unit: 'kcal',
            percentOfDailyNeeds: 19.85,
          },
          {
            name: 'Caffeine',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
        ],
      },
      {
        id: 99186,
        name: 'beef',
        amount: 0.75,
        unit: 'slices',
        nutrients: [
          {
            name: 'Alcohol',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 100.0,
          },
          {
            name: 'Vitamin B1',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 10.51,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Fat',
            amount: 0.03,
            unit: 'g',
            percentOfDailyNeeds: 24.61,
          },
          {
            name: 'Cholesterol',
            amount: 0.4,
            unit: 'mg',
            percentOfDailyNeeds: 15.07,
          },
          {
            name: 'Vitamin B12',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 3.33,
          },
          {
            name: 'Calcium',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 18.89,
          },
          {
            name: 'Selenium',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 56.8,
          },
          {
            name: 'Phosphorus',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 24.93,
          },
          {
            name: 'Vitamin B3',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 8.82,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 16.16,
          },
          {
            name: 'Vitamin D',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 3.59,
          },
          {
            name: 'Folate',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 8.94,
          },
          {
            name: 'Trans Fat',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 409.75,
          },
          {
            name: 'Copper',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 11.65,
          },
          {
            name: 'Vitamin K',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 9.81,
          },
          {
            name: 'Iron',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 7.78,
          },
          {
            name: 'Magnesium',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 12.31,
          },
          {
            name: 'Vitamin B5',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Manganese',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 33.27,
          },
          {
            name: 'Fluoride',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Protein',
            amount: 0.13,
            unit: 'g',
            percentOfDailyNeeds: 29.45,
          },
          {
            name: 'Fiber',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 15.43,
          },
          {
            name: 'Vitamin B2',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 10.55,
          },
          {
            name: 'Sodium',
            amount: 9.78,
            unit: 'mg',
            percentOfDailyNeeds: 18.48,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin E',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 2.93,
          },
          {
            name: 'Carbohydrates',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 16.1,
          },
          {
            name: 'Vitamin B6',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 8.13,
          },
          {
            name: 'Sugar',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 5.04,
          },
          {
            name: 'Zinc',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 11.04,
          },
          {
            name: 'Saturated Fat',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 60.73,
          },
          {
            name: 'Vitamin A',
            amount: 0.0,
            unit: 'IU',
            percentOfDailyNeeds: 16.87,
          },
          {
            name: 'Vitamin C',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 17.79,
          },
          {
            name: 'Potassium',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 7.24,
          },
          {
            name: 'Calories',
            amount: 0.8,
            unit: 'kcal',
            percentOfDailyNeeds: 19.85,
          },
          {
            name: 'Caffeine',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
        ],
      },
      {
        id: 10120420,
        name: 'farfalle pasta',
        amount: 1.0,
        unit: 'servings',
        nutrients: [
          {
            name: 'Alcohol',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 100.0,
          },
          {
            name: 'Vitamin B1',
            amount: 0.05,
            unit: 'mg',
            percentOfDailyNeeds: 10.51,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0.32,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Fat',
            amount: 0.85,
            unit: 'g',
            percentOfDailyNeeds: 24.61,
          },
          {
            name: 'Cholesterol',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 15.07,
          },
          {
            name: 'Vitamin B12',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 3.33,
          },
          {
            name: 'Calcium',
            amount: 11.76,
            unit: 'mg',
            percentOfDailyNeeds: 18.89,
          },
          {
            name: 'Selenium',
            amount: 35.39,
            unit: 'µg',
            percentOfDailyNeeds: 56.8,
          },
          {
            name: 'Phosphorus',
            amount: 105.84,
            unit: 'mg',
            percentOfDailyNeeds: 24.93,
          },
          {
            name: 'Vitamin B3',
            amount: 0.95,
            unit: 'mg',
            percentOfDailyNeeds: 8.82,
          },
          {
            name: 'Net Carbohydrates',
            amount: 40.02,
            unit: 'g',
            percentOfDailyNeeds: 16.16,
          },
          {
            name: 'Vitamin D',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 3.59,
          },
          {
            name: 'Trans Fat',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 409.75,
          },
          {
            name: 'Folate',
            amount: 10.08,
            unit: 'µg',
            percentOfDailyNeeds: 8.94,
          },
          {
            name: 'Folic Acid',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Copper',
            amount: 0.16,
            unit: 'mg',
            percentOfDailyNeeds: 11.65,
          },
          {
            name: 'Vitamin K',
            amount: 0.06,
            unit: 'µg',
            percentOfDailyNeeds: 9.81,
          },
          {
            name: 'Iron',
            amount: 0.73,
            unit: 'mg',
            percentOfDailyNeeds: 7.78,
          },
          {
            name: 'Magnesium',
            amount: 29.68,
            unit: 'mg',
            percentOfDailyNeeds: 12.31,
          },
          {
            name: 'Vitamin B5',
            amount: 0.24,
            unit: 'mg',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Manganese',
            amount: 0.51,
            unit: 'mg',
            percentOfDailyNeeds: 33.27,
          },
          {
            name: 'Protein',
            amount: 7.3,
            unit: 'g',
            percentOfDailyNeeds: 29.45,
          },
          {
            name: 'Fiber',
            amount: 1.79,
            unit: 'g',
            percentOfDailyNeeds: 15.43,
          },
          {
            name: 'Vitamin B2',
            amount: 0.03,
            unit: 'mg',
            percentOfDailyNeeds: 10.55,
          },
          {
            name: 'Sodium',
            amount: 3.36,
            unit: 'mg',
            percentOfDailyNeeds: 18.48,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0.1,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin E',
            amount: 0.06,
            unit: 'mg',
            percentOfDailyNeeds: 2.93,
          },
          {
            name: 'Carbohydrates',
            amount: 41.82,
            unit: 'g',
            percentOfDailyNeeds: 16.1,
          },
          {
            name: 'Vitamin B6',
            amount: 0.08,
            unit: 'mg',
            percentOfDailyNeeds: 8.13,
          },
          {
            name: 'Sugar',
            amount: 1.5,
            unit: 'g',
            percentOfDailyNeeds: 5.04,
          },
          {
            name: 'Zinc',
            amount: 0.79,
            unit: 'mg',
            percentOfDailyNeeds: 11.04,
          },
          {
            name: 'Saturated Fat',
            amount: 0.16,
            unit: 'g',
            percentOfDailyNeeds: 60.73,
          },
          {
            name: 'Vitamin A',
            amount: 0.0,
            unit: 'IU',
            percentOfDailyNeeds: 16.87,
          },
          {
            name: 'Vitamin C',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 17.79,
          },
          {
            name: 'Potassium',
            amount: 124.88,
            unit: 'mg',
            percentOfDailyNeeds: 7.24,
          },
          {
            name: 'Calories',
            amount: 207.76,
            unit: 'kcal',
            percentOfDailyNeeds: 19.85,
          },
        ],
      },
      {
        id: 1053,
        name: 'heavy cream',
        amount: 0.13,
        unit: 'cup',
        nutrients: [
          {
            name: 'Choline',
            amount: 5.0,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Alcohol',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 100.0,
          },
          {
            name: 'Vitamin B1',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 10.51,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0.47,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Fat',
            amount: 10.74,
            unit: 'g',
            percentOfDailyNeeds: 24.61,
          },
          {
            name: 'Cholesterol',
            amount: 33.62,
            unit: 'mg',
            percentOfDailyNeeds: 15.07,
          },
          {
            name: 'Vitamin B12',
            amount: 0.05,
            unit: 'µg',
            percentOfDailyNeeds: 3.33,
          },
          {
            name: 'Calcium',
            amount: 19.64,
            unit: 'mg',
            percentOfDailyNeeds: 18.89,
          },
          {
            name: 'Selenium',
            amount: 0.89,
            unit: 'µg',
            percentOfDailyNeeds: 56.8,
          },
          {
            name: 'Phosphorus',
            amount: 17.25,
            unit: 'mg',
            percentOfDailyNeeds: 24.93,
          },
          {
            name: 'Vitamin B3',
            amount: 0.02,
            unit: 'mg',
            percentOfDailyNeeds: 8.82,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0.84,
            unit: 'g',
            percentOfDailyNeeds: 16.16,
          },
          {
            name: 'Vitamin D',
            amount: 0.48,
            unit: 'µg',
            percentOfDailyNeeds: 3.59,
          },
          {
            name: 'Folic Acid',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Folate',
            amount: 1.19,
            unit: 'µg',
            percentOfDailyNeeds: 8.94,
          },
          {
            name: 'Vitamin K',
            amount: 0.95,
            unit: 'µg',
            percentOfDailyNeeds: 9.81,
          },
          {
            name: 'Copper',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 11.65,
          },
          {
            name: 'Iron',
            amount: 0.03,
            unit: 'mg',
            percentOfDailyNeeds: 7.78,
          },
          {
            name: 'Magnesium',
            amount: 2.08,
            unit: 'mg',
            percentOfDailyNeeds: 12.31,
          },
          {
            name: 'Lycopene',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin B5',
            amount: 0.08,
            unit: 'mg',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Manganese',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 33.27,
          },
          {
            name: 'Fluoride',
            amount: 0.89,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Protein',
            amount: 0.84,
            unit: 'g',
            percentOfDailyNeeds: 29.45,
          },
          {
            name: 'Fiber',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 15.43,
          },
          {
            name: 'Vitamin B2',
            amount: 0.06,
            unit: 'mg',
            percentOfDailyNeeds: 10.55,
          },
          {
            name: 'Sodium',
            amount: 8.03,
            unit: 'mg',
            percentOfDailyNeeds: 18.48,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 2.71,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin E',
            amount: 0.27,
            unit: 'mg',
            percentOfDailyNeeds: 2.93,
          },
          {
            name: 'Carbohydrates',
            amount: 0.84,
            unit: 'g',
            percentOfDailyNeeds: 16.1,
          },
          {
            name: 'Vitamin B6',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 8.13,
          },
          {
            name: 'Sugar',
            amount: 0.87,
            unit: 'g',
            percentOfDailyNeeds: 5.04,
          },
          {
            name: 'Zinc',
            amount: 0.07,
            unit: 'mg',
            percentOfDailyNeeds: 11.04,
          },
          {
            name: 'Saturated Fat',
            amount: 6.84,
            unit: 'g',
            percentOfDailyNeeds: 60.73,
          },
          {
            name: 'Vitamin A',
            amount: 437.33,
            unit: 'IU',
            percentOfDailyNeeds: 16.87,
          },
          {
            name: 'Vitamin C',
            amount: 0.18,
            unit: 'mg',
            percentOfDailyNeeds: 17.79,
          },
          {
            name: 'Potassium',
            amount: 28.26,
            unit: 'mg',
            percentOfDailyNeeds: 7.24,
          },
          {
            name: 'Calories',
            amount: 101.15,
            unit: 'kcal',
            percentOfDailyNeeds: 19.85,
          },
          {
            name: 'Caffeine',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
        ],
      },
      {
        id: 1033,
        name: 'parmesan cheese',
        amount: 0.13,
        unit: 'cup',
        nutrients: [
          {
            name: 'Choline',
            amount: 1.92,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Alcohol',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 100.0,
          },
          {
            name: 'Vitamin B1',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 10.51,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0.07,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Fat',
            amount: 3.23,
            unit: 'g',
            percentOfDailyNeeds: 24.61,
          },
          {
            name: 'Cholesterol',
            amount: 8.5,
            unit: 'mg',
            percentOfDailyNeeds: 15.07,
          },
          {
            name: 'Vitamin B12',
            amount: 0.15,
            unit: 'µg',
            percentOfDailyNeeds: 3.33,
          },
          {
            name: 'Calcium',
            amount: 148.0,
            unit: 'mg',
            percentOfDailyNeeds: 18.89,
          },
          {
            name: 'Selenium',
            amount: 2.81,
            unit: 'µg',
            percentOfDailyNeeds: 56.8,
          },
          {
            name: 'Phosphorus',
            amount: 86.75,
            unit: 'mg',
            percentOfDailyNeeds: 24.93,
          },
          {
            name: 'Vitamin B3',
            amount: 0.03,
            unit: 'mg',
            percentOfDailyNeeds: 8.82,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0.4,
            unit: 'g',
            percentOfDailyNeeds: 16.16,
          },
          {
            name: 'Vitamin D',
            amount: 0.06,
            unit: 'µg',
            percentOfDailyNeeds: 3.59,
          },
          {
            name: 'Folic Acid',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Folate',
            amount: 0.88,
            unit: 'µg',
            percentOfDailyNeeds: 8.94,
          },
          {
            name: 'Vitamin K',
            amount: 0.21,
            unit: 'µg',
            percentOfDailyNeeds: 9.81,
          },
          {
            name: 'Copper',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 11.65,
          },
          {
            name: 'Iron',
            amount: 0.1,
            unit: 'mg',
            percentOfDailyNeeds: 7.78,
          },
          {
            name: 'Magnesium',
            amount: 5.5,
            unit: 'mg',
            percentOfDailyNeeds: 12.31,
          },
          {
            name: 'Lycopene',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin B5',
            amount: 0.06,
            unit: 'mg',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Manganese',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 33.27,
          },
          {
            name: 'Protein',
            amount: 4.47,
            unit: 'g',
            percentOfDailyNeeds: 29.45,
          },
          {
            name: 'Fiber',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 15.43,
          },
          {
            name: 'Vitamin B2',
            amount: 0.04,
            unit: 'mg',
            percentOfDailyNeeds: 10.55,
          },
          {
            name: 'Sodium',
            amount: 200.25,
            unit: 'mg',
            percentOfDailyNeeds: 18.48,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0.94,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin E',
            amount: 0.03,
            unit: 'mg',
            percentOfDailyNeeds: 2.93,
          },
          {
            name: 'Carbohydrates',
            amount: 0.4,
            unit: 'g',
            percentOfDailyNeeds: 16.1,
          },
          {
            name: 'Vitamin B6',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 8.13,
          },
          {
            name: 'Sugar',
            amount: 0.1,
            unit: 'g',
            percentOfDailyNeeds: 5.04,
          },
          {
            name: 'Zinc',
            amount: 0.34,
            unit: 'mg',
            percentOfDailyNeeds: 11.04,
          },
          {
            name: 'Saturated Fat',
            amount: 2.05,
            unit: 'g',
            percentOfDailyNeeds: 60.73,
          },
          {
            name: 'Vitamin A',
            amount: 97.63,
            unit: 'IU',
            percentOfDailyNeeds: 16.87,
          },
          {
            name: 'Vitamin C',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 17.79,
          },
          {
            name: 'Potassium',
            amount: 11.5,
            unit: 'mg',
            percentOfDailyNeeds: 7.24,
          },
          {
            name: 'Calories',
            amount: 49.0,
            unit: 'kcal',
            percentOfDailyNeeds: 19.85,
          },
          {
            name: 'Caffeine',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
        ],
      },
      {
        id: 11304,
        name: 'peas',
        amount: 0.25,
        unit: 'cup',
        nutrients: [
          {
            name: 'Choline',
            amount: 10.3,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Alcohol',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 100.0,
          },
          {
            name: 'Vitamin B1',
            amount: 0.1,
            unit: 'mg',
            percentOfDailyNeeds: 10.51,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0.07,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Fat',
            amount: 0.14,
            unit: 'g',
            percentOfDailyNeeds: 24.61,
          },
          {
            name: 'Cholesterol',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 15.07,
          },
          {
            name: 'Vitamin B12',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 3.33,
          },
          {
            name: 'Calcium',
            amount: 9.06,
            unit: 'mg',
            percentOfDailyNeeds: 18.89,
          },
          {
            name: 'Selenium',
            amount: 0.65,
            unit: 'µg',
            percentOfDailyNeeds: 56.8,
          },
          {
            name: 'Phosphorus',
            amount: 39.15,
            unit: 'mg',
            percentOfDailyNeeds: 24.93,
          },
          {
            name: 'Vitamin B3',
            amount: 0.76,
            unit: 'mg',
            percentOfDailyNeeds: 8.82,
          },
          {
            name: 'Net Carbohydrates',
            amount: 3.15,
            unit: 'g',
            percentOfDailyNeeds: 16.16,
          },
          {
            name: 'Vitamin D',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 3.59,
          },
          {
            name: 'Folic Acid',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Folate',
            amount: 23.56,
            unit: 'µg',
            percentOfDailyNeeds: 8.94,
          },
          {
            name: 'Vitamin K',
            amount: 8.99,
            unit: 'µg',
            percentOfDailyNeeds: 9.81,
          },
          {
            name: 'Copper',
            amount: 0.06,
            unit: 'mg',
            percentOfDailyNeeds: 11.65,
          },
          {
            name: 'Iron',
            amount: 0.53,
            unit: 'mg',
            percentOfDailyNeeds: 7.78,
          },
          {
            name: 'Magnesium',
            amount: 11.96,
            unit: 'mg',
            percentOfDailyNeeds: 12.31,
          },
          {
            name: 'Lycopene',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin B5',
            amount: 0.04,
            unit: 'mg',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Manganese',
            amount: 0.15,
            unit: 'mg',
            percentOfDailyNeeds: 33.27,
          },
          {
            name: 'Protein',
            amount: 1.96,
            unit: 'g',
            percentOfDailyNeeds: 29.45,
          },
          {
            name: 'Fiber',
            amount: 2.07,
            unit: 'g',
            percentOfDailyNeeds: 15.43,
          },
          {
            name: 'Vitamin B2',
            amount: 0.05,
            unit: 'mg',
            percentOfDailyNeeds: 10.55,
          },
          {
            name: 'Sodium',
            amount: 1.81,
            unit: 'mg',
            percentOfDailyNeeds: 18.48,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin E',
            amount: 0.05,
            unit: 'mg',
            percentOfDailyNeeds: 2.93,
          },
          {
            name: 'Carbohydrates',
            amount: 5.22,
            unit: 'g',
            percentOfDailyNeeds: 16.1,
          },
          {
            name: 'Vitamin B6',
            amount: 0.06,
            unit: 'mg',
            percentOfDailyNeeds: 8.13,
          },
          {
            name: 'Sugar',
            amount: 2.06,
            unit: 'g',
            percentOfDailyNeeds: 5.04,
          },
          {
            name: 'Zinc',
            amount: 0.45,
            unit: 'mg',
            percentOfDailyNeeds: 11.04,
          },
          {
            name: 'Saturated Fat',
            amount: 0.03,
            unit: 'g',
            percentOfDailyNeeds: 60.73,
          },
          {
            name: 'Vitamin A',
            amount: 277.31,
            unit: 'IU',
            percentOfDailyNeeds: 16.87,
          },
          {
            name: 'Vitamin C',
            amount: 14.5,
            unit: 'mg',
            percentOfDailyNeeds: 17.79,
          },
          {
            name: 'Potassium',
            amount: 88.45,
            unit: 'mg',
            percentOfDailyNeeds: 7.24,
          },
          {
            name: 'Calories',
            amount: 29.36,
            unit: 'kcal',
            percentOfDailyNeeds: 19.85,
          },
          {
            name: 'Caffeine',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
        ],
      },
      {
        id: 1102047,
        name: 'salt and pepper',
        amount: 1.0,
        unit: 'servings',
        nutrients: [
          {
            name: 'Choline',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Alcohol',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 100.0,
          },
          {
            name: 'Vitamin B1',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 10.51,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Fat',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 24.61,
          },
          {
            name: 'Cholesterol',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 15.07,
          },
          {
            name: 'Vitamin B12',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 3.33,
          },
          {
            name: 'Calcium',
            amount: 0.12,
            unit: 'mg',
            percentOfDailyNeeds: 18.89,
          },
          {
            name: 'Selenium',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 56.8,
          },
          {
            name: 'Phosphorus',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 24.93,
          },
          {
            name: 'Vitamin B3',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 8.82,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 16.16,
          },
          {
            name: 'Vitamin D',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 3.59,
          },
          {
            name: 'Folic Acid',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Folate',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 8.94,
          },
          {
            name: 'Vitamin K',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 9.81,
          },
          {
            name: 'Copper',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 11.65,
          },
          {
            name: 'Iron',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 7.78,
          },
          {
            name: 'Magnesium',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 12.31,
          },
          {
            name: 'Lycopene',
            amount: 0.0,
            unit: 'µg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin B5',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Manganese',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 33.27,
          },
          {
            name: 'Fluoride',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Protein',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 29.45,
          },
          {
            name: 'Fiber',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 15.43,
          },
          {
            name: 'Vitamin B2',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 10.55,
          },
          {
            name: 'Sodium',
            amount: 193.79,
            unit: 'mg',
            percentOfDailyNeeds: 18.48,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 0.0,
          },
          {
            name: 'Vitamin E',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 2.93,
          },
          {
            name: 'Carbohydrates',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 16.1,
          },
          {
            name: 'Vitamin B6',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 8.13,
          },
          {
            name: 'Sugar',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 5.04,
          },
          {
            name: 'Zinc',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 11.04,
          },
          {
            name: 'Saturated Fat',
            amount: 0.0,
            unit: 'g',
            percentOfDailyNeeds: 60.73,
          },
          {
            name: 'Vitamin A',
            amount: 0.0,
            unit: 'IU',
            percentOfDailyNeeds: 16.87,
          },
          {
            name: 'Vitamin C',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 17.79,
          },
          {
            name: 'Potassium',
            amount: 0.04,
            unit: 'mg',
            percentOfDailyNeeds: 7.24,
          },
          {
            name: 'Calories',
            amount: 0.0,
            unit: 'kcal',
            percentOfDailyNeeds: 19.85,
          },
          {
            name: 'Caffeine',
            amount: 0.0,
            unit: 'mg',
            percentOfDailyNeeds: 0.0,
          },
        ],
      },
    ],
    caloricBreakdown: {
      percentProtein: 14.87,
      percentFat: 36.36,
      percentCarbs: 48.77,
    },
    weightPerServing: {
      amount: 137,
      unit: 'g',
    },
  },
  taste: {
    sweetness: 38.32,
    saltiness: 59.21,
    sourness: 25.19,
    bitterness: 24.48,
    savoriness: 53.63,
    fattiness: 100.0,
    spiciness: 10.0,
  },
  summary:
    'The recipe Farfalle with Peas, Ham and Cream can be made <b>in about 30 minutes</b>. This recipe serves 4. One portion of this dish contains around <b>15g of protein</b>, <b>16g of fat</b>, and a total of <b>397 calories</b>. For <b>77 cents per serving</b>, this recipe <b>covers 13%</b> of your daily requirements of vitamins and minerals. 3 people found this recipe to be scrumptious and satisfying. A mixture of salt and pepper, ham, farfalle pasta, and a handful of other ingredients are all it takes to make this recipe so scrumptious. It works well as a very reasonably priced main course. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 42%</b>, which is pretty good. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/farfalle-with-gorgonzola-ham-and-peas-149446">Farfalle With Gorgonzola, Ham And Peas</a>, <a href="https://spoonacular.com/recipes/ham-and-peas-farfalle-in-creamy-lemon-parmesan-sauce-646183">Ham and Peas Farfalle In Creamy Lemon Parmesan Sauce</a>, and <a href="https://spoonacular.com/recipes/pasta-with-ham-peas-and-cream-18210">Pasta With Ham, Peas And Cream</a>.',
  cuisines: [],
  dishTypes: ['side dish', 'lunch', 'main course', 'main dish', 'dinner'],
  diets: [],
  occasions: [],
  instructions:
    '<ol><li>Cook pasta according to package directions mentioned in the pasta box.</li><li> Remove from heat. When the pasta is cooked and drained, return to pan and add the sauce. Stir well and add the cheese on the pasta</li><li>In a skillet add the peas, butter, ham. Sautee for 5 minutes. Add the cream, salt and pepper and cook under medium heat for 5 to 10 minutes, or until the cream is slightly becoming thick.</li><li> Remove from heat. When the pasta is cooked and drained, return to pan and add the sauce. Stir well and add the cheese</li><li>Serve the pasta nice and hot in the mentioned servings.</li></ol>',
  analyzedInstructions: [
    {
      name: '',
      steps: [
        {
          number: 1,
          step: 'Cook pasta according to package directions.In a skillet add the peas, butter, ham.',
          ingredients: [
            {
              id: 1001,
              name: 'butter',
              localizedName: 'butter',
              image: 'butter-sliced.jpg',
            },
            {
              id: 20420,
              name: 'pasta',
              localizedName: 'pasta',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/fusilli.jpg',
            },
            {
              id: 11304,
              name: 'peas',
              localizedName: 'peas',
              image: 'peas.jpg',
            },
            {
              id: 10151,
              name: 'ham',
              localizedName: 'ham',
              image: 'ham-whole.jpg',
            },
          ],
          equipment: [
            {
              id: 404645,
              name: 'frying pan',
              localizedName: 'frying pan',
              image: 'https://spoonacular.com/cdn/equipment_100x100/pan.png',
            },
          ],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularScore: 47.989768981933594,
  spoonacularSourceUrl:
    'https://spoonacular.com/farfalle-with-peas-ham-and-cream-642583',
};
